import http from "node:http";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname=path.dirname(fileURLToPath(import.meta.url)), publicDir=path.join(__dirname,"public"), port=Number(process.env.PORT||8787);
const mime={".html":"text/html; charset=utf-8",".js":"application/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".svg":"image/svg+xml; charset=utf-8",".json":"application/json; charset=utf-8"};
const schemes=[["analog",[-28,0,28]],["complement",[0,18,180]],["mono-accent",[0,0,180]],["warm-accent",[0,24,150]],["cold-accent",[0,-24,210]],["split",[0,150,210]],["mono",[0,0,0]],["triad",[0,120,240]]];
const tones=["muted","normal","vivid"], toneCfg={muted:[[38,50,58],[34,52,64]],normal:[[58,70,76],[36,56,66]],vivid:[[76,88,92],[38,58,68]]};
const mod=(n,m)=>((n%m)+m)%m, hsl=(h,s,l)=>`hsl(${mod(Math.round(h),360)} ${s}% ${l}%)`;
function hash32(s){let h=2166136261>>>0;for(const ch of new TextEncoder().encode(s)){h^=ch;h=Math.imul(h,16777619)>>>0}h^=h>>>16;h=Math.imul(h,0x7feb352d);h^=h>>>15;h=Math.imul(h,0x846ca68b);h^=h>>>16;return h>>>0}
function palette(h){const [name,offs]=schemes[h%8],tone=tones[(h>>>5)%3],hue=(h>>>10)%360,[sat,light]=toneCfg[tone],bg=hsl(hue,tone==="vivid"?30:20,tone==="muted"?8:7);if(name==="mono-accent")return{name,tone,hue,background:bg,base:hsl(hue,18,42),frame:hsl(hue,10,68),core:hsl(hue+180,sat[2],light[2])};if(name==="mono")return{name,tone,hue,background:bg,base:hsl(hue,sat[0],32),frame:hsl(hue,sat[1],52),core:hsl(hue,sat[2],72)};const hs=offs.map(o=>mod(hue+o,360));return{name,tone,hue,background:bg,base:hsl(hs[0],sat[0],light[0]),frame:hsl(hs[1],sat[1],light[1]),core:hsl(hs[2],sat[2],light[2])}}
const strip=s=>s.replace(/^.*?<g /s,'<g ').replace(/<\/svg>\s*$/,'');
async function avatar(seed,size){const manifest=JSON.parse(await fs.readFile(path.join(publicDir,"assets-svg/manifest.json"),"utf8")),h=hash32(seed),a=manifest.assets,p=palette(h),pick=(x,n)=>x[n%x.length],base=pick(a.bases,h),frame=pick(a.frames,h>>>8),core=pick(a.cores,h>>>16);const read=(folder,name)=>fs.readFile(path.join(publicDir,"assets-svg",folder,name+".svg"),"utf8");const [b,f,c]=await Promise.all([read("bases",base),read("frames",frame),read("cores",core)]);const layer=(src,color)=>`<g color="${color}" style="color:${color}">${strip(src).replaceAll('#fff','currentColor')}</g>`;return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 512 512" role="img" aria-label="${base} ${frame} ${core}"><rect width="512" height="512" fill="${p.background}"/>${layer(b,p.base)}${layer(f,p.frame)}${layer(c,p.core)}</svg>`}
async function sendFile(res,file){try{const data=await fs.readFile(file);res.writeHead(200,{"Content-Type":mime[path.extname(file)]||"application/octet-stream"});res.end(data)}catch{res.writeHead(404);res.end("Not found")}}
http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host}`);const m=u.pathname.match(/^\/api\/avatar(?:\/([^/]+))?(?:\.svg)?$/);if(m){const seed=decodeURIComponent(m[1]||u.searchParams.get("seed")||"avatar"),size=Math.max(16,Math.min(2048,Number(u.searchParams.get("size"))||512));const body=await avatar(seed,size);res.writeHead(200,{"Content-Type":"image/svg+xml; charset=utf-8","Cache-Control":"public, max-age=31536000, immutable","X-Avatar-Seed":seed});return res.end(body)}const rel=u.pathname==="/"?"demo.html":u.pathname.replace(/^\//,"");await sendFile(res,path.join(publicDir,path.normalize(rel).replace(/^\.\.(\/|\\|$)/,""))) }).listen(port,"0.0.0.0",()=>console.log(`avatar-generator http://localhost:${port}`));
